name: Sync to Website Bucket

on:
  push:
    branches:
    - develop

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  CopyToS3:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::153765495495:role/github-actions-sync-to-website-bucket
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: 'us-east-1'
      # Hello from AWS: WhoAmI
      - name: S3 sync
        run: |
          aws s3 sync . s3://andrewzick.com --no-progress --acl public-read --delete --exclude 'terraform/*' --exclude '.git/*' --exclude '.gitignore' --exclude '.github/*' --exclude '.dockerignore'
